version: '3'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    ports:
      - ${MONGO_PORT}:27017
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - mongo
    volumes:
      - ./.env:/app/.env
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
    depends_on:
      - server
    volumes:
      - ./.env:/app/.env